### ISSUE TITLE
Meaning of LWW?

### ISSUE THREAD

**Issue by leehambley** [gritzko/ron#1]
From the docs there's some quotes like:

> data type UUID, e.g. `lww`,

I've not run across this term before, some cursory ~~Googling~~ Yandexing suggests it means "last write wins" which in the context of this log structured replicable data type would fit.

Could you clarify in the docs, or here, and I can send a Pr with the docs I'd have liked to have seen included?

**Comment by gritzko** [comment]
https://github.com/gritzko/ron/blob/master/rdt/lww.go#L7

I added a comment like this.
Which docs do you like to be included?

**Comment by leehambley** [comment]
Perfect, thanks - I missed it in the readme seeing `lww` five times :)
